# Generated by Django 4.2 on 2023-09-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testTask', '0002_alter_lesson_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_view',
            name='user_id',
        ),
        migrations.AddField(
            model_name='lesson_view',
            name='access_user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='testTask.product_access'),
        ),
    ]
