# Generated by Django 4.2 on 2023-09-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testTask', '0003_remove_lesson_view_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_access',
            name='user_id',
        ),
    ]
