# Generated by Django 4.2 on 2023-09-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testTask', '0005_product_access_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_view',
            name='access_user_id',
        ),
        migrations.DeleteModel(
            name='Product_Access',
        ),
    ]
