# Generated by Django 4.2 on 2023-09-24 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTask', '0007_user_name_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_view',
            name='date_time_field',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 8, 52, 43, 577975, tzinfo=datetime.timezone.utc)),
        ),
    ]
