# Generated by Django 4.2 on 2023-09-24 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testTask', '0008_lesson_view_date_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_view',
            name='date_time_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
